### ISSUE TITLE
Error about collect.py file

### ISSUE THREAD

**Issue by ll906875341** [ds4dm/branch-search-trees#1]
Dear professor,

Sorry for bothering.

When I run the collect.py file. I got this error,

`AttributeError: 'pyscipopt.scip.Model' object has no attribute 'getNNodesLeft'`

This is my 'paths' setting

`paths = {`
`    'MYSYSTEM': {`
`        'out_dir': 'new_dataset', `
`        'instances_dir': 'branch-search-trees-dataset/train_instances/', `
`        'cutoff_dict': 'branch-search-trees-dataset/cutoff_dict.pkl',  `
`    },`
`}`

This is my run command
`python collect.py -n air05.mps.gz \`
`                  -s 0 \`
`                  -k 10 \`
`                  --setting sandbox \`
`                  --system MYSYSTEM \`
`                  -v`

The version of PySCIPOpt is 1.4.9, which is the same as in requirements.txt and I checked the functions inside the model through the dir(model) method, and did not find functions such as getNNodesLeft, getCandsState, getNodeState, and getMIPState.

Could you help me? How do you think about this error? Thank you very much, professor.

Sincerely.

**Comment by vis-opt** [comment]
It's not a bother at all.

I suspect you are using the default version of PySCIPOPT, but like we note here in our readme https://github.com/ds4dm/branch-search-trees#installation-and-dependencies, you have to install our customized version of PySCIPOPT. We coded up our own customized version that has all the corresponding data collection methods that you mentioned. Please refer to the above link in our readme for installation instructions. 

Can you verify that you are getting this error with our custom version of PySCIPOPT?

**Comment by ll906875341** [comment]
Thank you very much for your help, my problem has been solved.

Sincerely.
